name: sokrio
description: Sokrio test app
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  get: ^4.6.5
  intl: ^0.17.0
  sqflite: ^2.0.2+1
  geocoding: ^2.0.4
  geolocator: ^9.0.0
  google_fonts: ^3.0.1
  permission_handler: ^10.0.0
  flutter_screenutil: ^5.5.3+2
  cached_network_image: ^3.2.1
  connectivity_plus: ^2.3.5
  card_swiper: ^2.0.4
  flutter_svg: ^1.1.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/